import { useEffect, useState } from 'react';
import { Armchair, ChefHat, QrCode } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { tenantService } from '../../services/tenant.service';
import type { RestaurantOrder, RestaurantTable } from '../../types';

export default function RestaurantPage() {
  const [tables, setTables] = useState<RestaurantTable[]>([]); const [orders, setOrders] = useState<RestaurantOrder[]>([]); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); Promise.all([tenantService.getTables(), tenantService.getOrders()]).then(([nextTables, nextOrders]) => { setTables(nextTables); setOrders(nextOrders); }).finally(() => setLoading(false)); }; useEffect(load, []);
  const cycle = async (table: RestaurantTable) => { const statuses: RestaurantTable['status'][] = ['available', 'occupied', 'billing']; const next = statuses[(statuses.indexOf(table.status) + 1) % statuses.length]; await tenantService.updateTable(table.id, next); load(); };
  const openQr = async (table: RestaurantTable) => { const qr = await tenantService.getTableQr(table.id); window.open(qr.qrImageUrl, '_blank', 'noopener,noreferrer'); };
  return <div className="space-y-6"><div><span className="text-[11px] font-bold uppercase tracking-widest text-violet-600">Gastronomía</span><h1 className="font-editorial text-3xl font-bold text-zinc-900 dark:text-white">Salón y comandas</h1><p className="text-sm text-zinc-500">Estado de mesas y pedidos activos en tiempo real.</p></div>{loading ? <LoadingSpinner size="lg" label="Cargando salón..." /> : <div className="grid gap-5 lg:grid-cols-2"><Card variant="glass"><CardHeader><CardTitle><Armchair className="mr-2 inline" size={18} />Mesas</CardTitle></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{tables.map((table) => <div key={table.id} className="space-y-1"><Button variant={table.status === 'available' ? 'outline' : 'soft'} className="h-20 w-full flex-col" onClick={() => cycle(table)}><strong>Mesa {table.number}</strong><span className="text-[10px]">{table.status}</span></Button><button className="flex w-full items-center justify-center gap-1 text-[10px] font-semibold text-violet-600" onClick={() => openQr(table)}><QrCode size={12} />Generar QR</button></div>)}{tables.length === 0 && <p className="col-span-3 text-sm text-zinc-500">No hay mesas configuradas.</p>}</div></CardContent></Card><Card variant="glass"><CardHeader><CardTitle><ChefHat className="mr-2 inline" size={18} />Pedidos activos</CardTitle></CardHeader><CardContent><div className="space-y-3">{orders.filter((order) => !['paid', 'canceled'].includes(order.status)).map((order) => <div key={order.id} className="rounded-xl border border-zinc-200 p-3 dark:border-zinc-800"><div className="flex justify-between text-sm font-semibold"><span>{order.table ? `Mesa ${order.table.number}` : 'Pedido'}</span><span className="text-xs text-violet-600">{order.status}</span></div><p className="mt-1 text-xs text-zinc-500">{order.lines.map((line) => `${line.quantity}× ${line.catalogItem?.title ?? 'Ítem'}`).join(' · ')}</p></div>)}{orders.length === 0 && <p className="text-sm text-zinc-500">No hay pedidos activos.</p>}</div></CardContent></Card></div>}</div>;
}
