name: Release # Contract tracked by backoffice issue #31

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: aurea-io/aurea-ci/.github/workflows/release.yml@f23cac745fb26144d4503c6666d0e113eac4a5d1
